package com.example.domain.appstrings

import kotlinx.serialization.Serializable

@Serializable
data class AppStrings(
    val facturaListTitle: String,
    val popUpTitle: String,
    val popUpMessage: String,
    val closePopUp: String,
    val loadingScreenTitle: String,
    val filterPopUpTitle: String,
    val filterPopUpMessage: String,
    val filterScreenTitle: String,
    val filterDateTitle: String,
    val filterStartDateTitle: String,
    val filterDateButtonText: String,
    val filterEndDateTitle: String,
    val filterCheckBoxTitle: String,
    val filterImporteTitle: String,
    val filterApplyButtonText: String,
    val filterResetButtonText: String,
    val filterPopUpConfirmText: String,
    val filterPopUpCloseText: String,
    val smartSolarInstallationTitle: String,
    val smartSolarEnergyScreenText: String,
    val smartSolarDetailsCodeFieldTitle: String,
    val smartSolarDetailsRequestStatusTitle: String,
    val smartSolarDetailsTypeTitle: String,
    val smartSolarDetailsCompensationFieldTitle: String,
    val smartSolarDetailsPowerFieldTitle: String,
    val facturaListScreenAppbarTitle: String,
    val smartSolarDetailsLoadingText: String,
    val smartSolarDialogTitle: String,
    val smartSolarDialogMessage: String,
    val smartSolarDialogButtonText: String,
    val smartSolarAppbarTitle: String,
    val smartSolarScreenTitle: String,
    val facturaDescStatePagada: String,
    val facturaDescStateAnulada: String,
    val facturaDescStateCuotaFija: String,
    val facturaDescStatePendienteDePago: String,
    val facturaDescStatePlanDePago: String,
    val smartSolarInstallationTabTitle: String,
    val smartSolarEnergyTabTitle: String,
    val smartSolarDetailsTabTitle: String,
    val smartSolarInstallationAutoconsumptionText: String,
    val homeScreenFacturasCardTitle: String,
    val homeScreenSmartSolarCardTitle: String,
    val homeScreenTitle: String,
    val switchUseMockDataAffirmativeText: String,
    val switchUseMockDataNegativeText: String,
    val snackbarUsingMockMessage: String,
    val snackbarUsingApiMessage: String,
    val crashButtonText: String,
    val noDataScreenText : String,
    val eurosChartLabel : String,
)